import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/Providers";
import SideNav from "@/components/custom/SideNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tools",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-color-mode="dark">
      <body className={inter.className}>
        <Providers>
          <div
          className="flex"
          >
            <SideNav />
            <div
            className="flex-grow max-h-screen  overflow-auto p-5"
            >
              {children}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
